// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ZkhKqqf1EIJaZXVBpFWyQGfdpc5U87Y',
    appId: '1:607429581854:web:3a905e161537e01a5f220f',
    messagingSenderId: '607429581854',
    projectId: 'andriod-firebase-563c8',
    authDomain: 'andriod-firebase-563c8.firebaseapp.com',
    storageBucket: 'andriod-firebase-563c8.appspot.com',
    measurementId: 'G-FTXGFV5G7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZklezagrbwi5NwpY7l-VrTULLMo_vKlw',
    appId: '1:607429581854:android:1af6ad30ae36628e5f220f',
    messagingSenderId: '607429581854',
    projectId: 'andriod-firebase-563c8',
    storageBucket: 'andriod-firebase-563c8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ZkhKqqf1EIJaZXVBpFWyQGfdpc5U87Y',
    appId: '1:607429581854:web:83ed0fbe86484ff45f220f',
    messagingSenderId: '607429581854',
    projectId: 'andriod-firebase-563c8',
    authDomain: 'andriod-firebase-563c8.firebaseapp.com',
    storageBucket: 'andriod-firebase-563c8.appspot.com',
    measurementId: 'G-P0EQN9GE52',
  );
}
